[workspace]
members = [
    "asg_core",
    "parser_core",
    "formatter_core",
    "synapse_cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Synapse Team"]
license = "MIT"