[package]
name = "upir_to_spirv"
version = "0.1.0"
edition = "2021"

[dependencies]
upir_core = { path = "../upir_core" }
spirv_builder = "0.7"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
