[package]
name = "synapse_runtime"
version = "0.1.0"
edition = "2021"
description = "Minimal runtime support for Synapse (UART prototype)."

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"