[package]
name = "upir_to_qsim"
version = "0.1.0"
edition = "2021"

[dependencies]
upir_core = { path = "../upir_core" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
