[package]
name = "upir_core"
version = "0.1.0"
edition = "2021"
authors = ["The Synapse Team"]
description = "Universal Polymorphic Intermediate Representation (UPIR) core for Synapse"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"